<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxuAxOl9Lw18Ch02fe2w7'."\n".'F7vTYL5b7e/7w+K2I+ntjytGKLRd2Y7G6M8Wb3W3TMnU3wsxjLBuxNZB0MzZLgzz'."\n".'s3PD5hPll66MScHZeOH0FqeSYx8dw+hJwy7m3MmqdoOK41htijP7sMsVC7xDuUc8'."\n".'0TMk82KanYxJuZuiXv468boZUr1gI3MXJUznFHKE5nRWoBsjuhJiSCy87zdYGXns'."\n".'cEHZiWwlcSURa3+eTNhQ0fK+m0ApJS4Ji3RO1xoZJ2X6K85Yelc+8Y0seV1RfsFJ'."\n".'zZiRtwuU5ce7+7z4+spO7y0/QezHkCjPSjZNwYVVPrOaR8hGIdhde1uk6aealsur'."\n".'CQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
