<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHv0k7LN\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHv0k7LN/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHv0k7LN.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHv0k7LN\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHv0k7LN\appAppKernelProdContainer([
    'container.build_hash' => 'Hv0k7LN',
    'container.build_id' => 'aed3a382',
    'container.build_time' => 1709747177,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHv0k7LN');
